### ISSUE TITLE
Allow showing passwords on the passwords overview page

### ISSUE THREAD

**Issue by palant** [palant/easypasswords#11]
It should be possible to show the passwords (after accepting a warning of course), in order for those to be printed as a paper backup.

**Comment by fhd** [comment]
To add another use case: One occasionally has to see passwords in order to type them in, e.g. on mobile (even with #25 solved, or a proper mobile app even, I don't see this use case disappear).

Currently the best way to do that is to copy the password into the clipboard and then into some other text field. One of the most readily available text fields is the browser's URL bar, which is however a dangerous place for sensitive information, since accidentally hitting return will send it to the browser's default search engine.
