### ISSUE TITLE
Make using site aliasing more straightforward

### ISSUE THREAD

**Issue by r-a-y** [palant/easypasswords#29]
I had a hard time trying to figure out how to use this feature, since I couldn't find any documentation about this.

After some trial-and-error, here are some quick instructions:
1. Click on the Easy Passwords icon.
2. Under "Website Name", click on the edit notepad icon.
3. Edit the website name to whatever website you use for the main login.  For example, if your main login is to `example.com`, and you land on a subdomain such as `a.example.com` and share the same login credentials as the main site, you should edit the website name from `a.example.com` to `example.com`.
4. Save.

Hope that helps.

Thanks for creating this project, @palant!

**Comment by kzar** [comment]
I have to agree the site aliasing feature is really confusing at the moment. I had to go and read your blog post before I could understand what was happening. Perhaps instead of improving the documentation we should figure out a way it can work that's less confusing?

Perhaps there should be a button "This domain is an alias" or something like that? When clicked it could prompt the user to type the alias domain. Maybe we could only display that button when the current domain doesn't already have any (non legacy) passwords?

Since LastPass offers a search bar at the top of the popup panel which allows the user to search for other domains, perhaps we should do something similar? When I first saw the edit button next to the current domain that's what I was expecting it to do. Provide a way I can view passwords for a different domain. (If I'm currently browsing GitHub I might still want to view my passwords for PayPal, it doesn't mean I want to alias the two domains.)

**Comment by palant** [comment]
I agree, aliasing functionality should simply me more obvious - I changed the title of this issue to reflect this. Here is what I have so far:

![Adding an alias](http://i.imgur.com/qFh4Hyf.png)

![Setting site name](http://i.imgur.com/yEo0sfX.png)

This clearly separates the two scenarios: website without passwords (adding an alias) and special page (no site is set), different message is shown for those. Websites with existing passwords won't show any link.

I'll change the display for websites with alias soon.

**Comment by palant** [comment]
These messages seem to be good enough now:

![Website without any passwords](http://i.imgur.com/j8SHIiO.png)

![Website that is an alias](http://i.imgur.com/J7BfE42.png)

![Special page](http://i.imgur.com/zWChN9D.png)

This way it should hopefully be obvious enough.

**Comment by kzar** [comment]
Yea, way clearer now :+1:
